#!/usr/bin/env bash
# displays the content of the file /etc/passwd.

while read line; do
	USERNAME=$(echo "$line" | cut -d: -f1)
	USER_ID=$(echo "$line" | cut -d: -f3)
	HOME=$(echo "$line" | cut -d: -f6)
	echo "$USERNAME:$USER_ID:$HOME"
done < "/etc/passwd"
